type = "javascript"
name = "website-reverse-proxy"
account_id = "729c76109998a58d9543b615f18832ff"
zone_id = "036fdaca5aae1198de521c69944c1c65"
routes = ["https://www.openactive.io/activity-list/activity-list.jsonld", "https://www.openactive.io/accessibility-support/accessibility-support.jsonld", "https://www.openactive.io/facility-types/facility-types.jsonld", "https://www.openactive.io/assets/openactive-logo-small.png"]
